"""
Protocol PDF (made by fs-protocolgenerator): page plan and redaction.

Per category a protocol holds a head page, a podium page (generated by the
protocol generator: letter-spaced "PODIUM" eyebrow, Raleway fonts, a photo),
the category result, and per segment the segment result, panel of judges and
judges details per skater — the last four are FS Manager PDFs inserted as is.
Withdrawn skaters are listed by name under a "Withdrawn" heading on the result
sheets.

`plan()` lists every page where a selected skater appears, with its type and
the action that will be taken: a podium page is removed entirely (its photo
shows the skater), every other page has the name and club redacted. `plan_hash`
binds a plan to the exact protocol bytes and selection, so `apply()` can refuse
to run on anything other than the plan the user confirmed.
"""
import hashlib
import json

import pymupdf

import names
import pdf_redact

PODIUM = "podium"
RESULTS = "results"
SEGMENT_RESULTS = "segment_results"
JUDGES_DETAILS = "judges_details"
PANEL = "panel"
WITHDRAWN = "withdrawn_list"
OTHER = "other"

PAGE_TYPE_LABELS = {
    PODIUM: "Podium",
    RESULTS: "Results",
    SEGMENT_RESULTS: "Segment results",
    JUDGES_DETAILS: "Judges details per skater",
    PANEL: "Panel of judges",
    WITHDRAWN: "Withdrawn list",
    OTHER: "Other",
}

ACTION_REMOVE = "remove_page"
ACTION_REDACT = "redact"


class PlanMismatch(Exception):
    pass


def _compact(text: str) -> str:
    return "".join(text.split()).upper()


def classify(page) -> str:
    text = page.get_text()
    compact = _compact(text)
    is_fsm = "PRINTED:" in compact
    if "JUDGESDETAILSPERSKATER" in compact:
        return JUDGES_DETAILS
    if "PANELOFJUDGES" in compact:
        return PANEL
    if not is_fsm:
        # Generated pages: the podium carries the eyebrow near the top.
        top = page.get_text(clip=pymupdf.Rect(0, 0, page.rect.width, page.rect.height * 0.3))
        if "PODIUM" in _compact(top):
            return PODIUM
        return OTHER
    if "RESULT" in compact:
        if "TOTALSEGMENTSCORE" in compact or "SEGMENTSCORE" in compact:
            return SEGMENT_RESULTS
        return RESULTS
    return OTHER


def _category_label(page) -> str:
    """The FS Manager sheet's category/segment heading (second bold line)."""
    lines = []
    for b in page.get_text("dict").get("blocks", []):
        for line in b.get("lines", []):
            t = "".join(s["text"] for s in line["spans"]).strip()
            if t:
                lines.append((line["bbox"][1], t))
    lines.sort()
    return lines[1][1] if len(lines) > 1 else ""


def protocol_digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def plan(data: bytes, skater_names, clubs=None):
    """The pages a selection touches: [{page, type, action, skaters}] (1-based
    page numbers, skaters = indexes into skater_names). Writes nothing."""
    doc = pymupdf.open(stream=data, filetype="pdf")
    try:
        hits = pdf_redact.find_hits(doc, skater_names, clubs)
        by_page = {}
        for h in hits:
            by_page.setdefault(h.page, []).append(h)
        entries = []
        for pno in sorted(by_page):
            page = doc[pno]
            ptype = classify(page)
            page_hits = by_page[pno]
            if ptype != PODIUM and all(h.in_withdrawn for h in page_hits):
                ptype = WITHDRAWN
            entries.append({
                "page": pno + 1,
                "type": ptype,
                "typeLabel": PAGE_TYPE_LABELS[ptype],
                "action": ACTION_REMOVE if ptype == PODIUM else ACTION_REDACT,
                "skaters": sorted({h.skater for h in page_hits}),
                "heading": _category_label(page) if ptype != PODIUM else "",
            })
        return {"pageCount": doc.page_count, "pages": entries}
    finally:
        doc.close()


def plan_hash(data: bytes, plan_obj, selection_ids) -> str:
    payload = json.dumps({
        "protocol": protocol_digest(data),
        "pages": [(e["page"], e["type"], e["action"], e["skaters"]) for e in plan_obj["pages"]],
        "selection": list(selection_ids),
    }, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode()).hexdigest()


def _image_digests(doc, pnos):
    out = set()
    for pno in pnos:
        for img in doc[pno].get_images(full=True):
            try:
                out.add(hashlib.sha256(doc.xref_stream_raw(img[0])).hexdigest())
            except Exception:
                pass
    return out


def all_image_digests(data: bytes):
    doc = pymupdf.open(stream=data, filetype="pdf")
    try:
        out = set()
        for xref in range(1, doc.xref_length()):
            try:
                if doc.xref_get_key(xref, "Subtype")[1] == "/Image":
                    out.add(hashlib.sha256(doc.xref_stream_raw(xref)).hexdigest())
            except Exception:
                pass
        return out
    finally:
        doc.close()


def apply(data: bytes, skater_names, clubs, selection_ids, confirmed_hash: str):
    """Produce the redacted protocol for a confirmed plan. Raises PlanMismatch
    unless `confirmed_hash` equals the hash of the plan recomputed from these
    very bytes and this selection. Returns (new_bytes, info)."""
    current = plan(data, skater_names, clubs)
    if not confirmed_hash or plan_hash(data, current, selection_ids) != confirmed_hash:
        raise PlanMismatch("protocol or selection changed since the plan was confirmed")

    doc = pymupdf.open(stream=data, filetype="pdf")
    try:
        remove = [e["page"] - 1 for e in current["pages"] if e["action"] == ACTION_REMOVE]
        redact_pages = [e["page"] - 1 for e in current["pages"] if e["action"] == ACTION_REDACT]
        keep = [p for p in range(doc.page_count) if p not in set(remove)]
        removed_only_images = _image_digests(doc, remove) - _image_digests(doc, keep)

        hits = pdf_redact.find_hits(doc, skater_names, clubs, pages=redact_pages)
        written = pdf_redact.redact(doc, hits)
        if remove:
            doc.delete_pages(remove)
        # Page numbers of the written replacement boxes, after deletion.
        shift = {old: old - sum(1 for r in remove if r < old) for old in written}
        written_after = {shift[p]: boxes for p, boxes in written.items()}
        new = pdf_redact.save_bytes(doc)
    finally:
        doc.close()
    return new, {
        "plan": current,
        "removedPages": [p + 1 for p in remove],
        "redactedPages": [p + 1 for p in redact_pages],
        "removedImageDigests": sorted(removed_only_images),
        "written": written_after,
        "keptPagesOriginal": keep,
        "hits": hits,
    }
